apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configs
data:
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '54322'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cmlvdmVyckBpbjIy

---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-users-storage

  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/users'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-users-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-users
  # namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-users
  template:
    metadata:
      labels:
        app: postgres-users
    spec:
      containers:
        - name: postgres-users
          image: postgres:13.2-alpine
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 54322
          envFrom:
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb-users
      volumes:
        - name: postgresdb-users
          persistentVolumeClaim:
            claimName: postgres-users-storage-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-users
spec:
  selector:
    app: postgres-users
  ports:
    - port: 54322
