apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-inventory-configs
data:
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '54323'
---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-inventory-storage

  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/inventory'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-inventory-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-inventory
  # namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventory
  template:
    metadata:
      labels:
        app: postgres-inventory
    spec:
      containers:
        - name: postgres-inventory
          image: postgres:13.2-alpine
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 54323
          envFrom:
            - secretRef:
                name: all-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb-inventory
      volumes:
        - name: postgresdb-inventory
          persistentVolumeClaim:
            claimName: postgres-inventory-storage-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory
spec:
  selector:
    app: postgres-inventory
  ports:
    - port: 54323
