apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-orders-db-configs
data:
  POSTGRES_HOST: 'postgres'
  POSTGRES_PORT: '54321'
---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-orders-db-storage

  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/orders-db'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-db-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-orders-db
  # namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orders-db
  template:
    metadata:
      labels:
        app: postgres-orders-db
    spec:
      containers:
        - name: postgres-orders-db
          image: postgres:13.2-alpine
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 54321
          envFrom:
            - secretRef:
                name: all-secret-2 
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb-orders-db
      volumes:
        - name: postgresdb-orders-db
          persistentVolumeClaim:
            claimName: postgres-orders-db-storage-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-orders-db
spec:
  selector:
    app: postgres-orders-db
  ports:
    - port: 54321