apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cmlvdmVyckBpbjIy
  SECRET_KEY: MDlkMjVlMDk0ZmFhNmNhMjU1NmM4MTgxNjZiN2E5NTYzYjkzZjcwOTlmNmYwZjRjYWE2Y2Y2M2I4OGU4ZDNlNw==
  SECRET_KEY_USERS: MDlkMjVlMDk0ZmFhNmNhMjU1NmM4MTgxNjZiN2E5NTYzYjkzZjcwOTlmNmYwZjRjYWE2Y2Y2M2I4OGU4ZDAzOTU2NDk3Nzc=
  ALGORITHM: SFMyNTY=
  ACCESS_TOKEN_EXPIRE_MINUTES: NjA=
  ELASTIC_USER: ZWxhc3RpYw==
  ELASTIC_PASSWORD: UlZBN3RDMnA4ZkU2aXlyQWRydko=


